chore: remove deployment related code
mento-protocol/mento-core pull request #100
Opened 2023-01-12 17:03 UTC by bayological

### Description

This change removes all deployment-related code that will be added to the `mento-core-ts` and `mento-deployment` repos.

### Other changes

- Renamed package from "@mentolabs/core" to "@mento-protocol/core-contracts"

### Tested

- Code compiles, and all tests pass. The removed code does not impact protocol functionality.

### Related issues

- Fixes https://github.com/mento-protocol/mento-core-ts/issues/1
- Fixes #97 

### Backwards compatibility

N/A

### Documentation

N/A

2023-01-12 22:04 UTC, philbow61 requested changes
LGTM besides the comments I left regarding the artifacts of the npm package and mento-labs renaming

2023-01-18 17:28 UTC, bayological commented on package.json
>      "build": "tsc"
Thanks @philbow61, these changes have been reverted.

2023-01-19 06:46 UTC, bowd approved these changes
LGTM 🚢, left one small comment but didn't want to block it with request changes.

2023-01-19 06:46 UTC, bowd commented on package.json
> +  "name": "@mento-protocol/core",
Maybe it would make sense to name this `@mento-protocol/core-contracts`, because the `mento-protocol/core-ts` repo will export the `@mento-protocol/core` NPM package.

2023-01-19 09:16 UTC, philbow61 approved these changes
LGTM 😎 but a bit unsure on where to use Mento Labs vs Mento Protocol

2023-01-19 09:16 UTC, philbow61 commented on LICENSE
> -   Copyright 2022 Mento Labs
Do we want to keep the licenses for our repo or just rename the line to Mento Protocol?

2023-01-19 09:16 UTC, philbow61 commented on package.json
>      "name": "Mento Labs"
```suggestion
    "name": "Mento Protocol"
```
not sure /:

2023-01-19 14:38 UTC, bayological commented on package.json
>      "name": "Mento Labs"
We, as Mento Labs, built the project/tooling that helps facilitate the deployment of the Mento Protocol. If someone were to look at this, maybe they wanted to ask questions they know to reach out to us(Mento Labs). Having the author as would imply that the protocol wrote itself & the deployment repo :D

2023-01-19 14:39 UTC, bayological commented on LICENSE
> -   Copyright 2022 Mento Labs
Let's add a license before we deploy. We need to talk about which licence we should be using.

2023-01-19 14:40 UTC, philbow61 commented on package.json
>      "name": "Mento Labs"
hahahah now I get it 👍

2023-01-19 14:44 UTC, merged