fix: initilize local variables
mento-protocol/mento-core pull request #116
Opened 2023-01-26 22:06 UTC by bayological

### Description

Update to initialize local variables.

### Other changes

None

### Tested

- Unit tests run and pass as before

### Related issues

- Closes #104 

### Backwards compatibility

N/A

### Documentation

N/A

2023-01-26 22:36 UTC, philbow61 approved these changes
marvelous 🚢

2023-01-27 08:36 UTC, ninocomputer approved these changes
genius 👍🏼

2023-01-27 11:34 UTC, bowd requested changes

2023-01-27 11:34 UTC, bowd commented on contracts/Reserve.sol
> +    uint256 spendingLimitForThisAsset = 0;
Huh, this is actually a funny one. This actually is the bug I mentioned briefly in our 1:1.
Compare the implementation of this function to the one in `transferGold`, focus on the usage of `spendingLimit` vs `spendingLimitForThisAsset`. 

This issue needs more refactoring, also @ninocomputer take a look here cose I think you implemented this.

2023-01-27 15:09 UTC, bayological commented on contracts/Reserve.sol
> +    uint256 spendingLimitForThisAsset = 0;
@bowd The difference I see is that the `spendingLimit` is declared as a public state variable, whereas `spendingLimitForThisAsset` is function scoped, which aligns with what slither is saying. What was the bug? I don't remember 🥲

2023-01-27 17:18 UTC, bowd commented on contracts/Reserve.sol
> +    uint256 spendingLimitForThisAsset = 0;
Well, in the `transferGold` logic the `spendingLimit` being a public state var means that the value that is calculated during the execution is actually cached between executions and is reset when the condition – `if (currentDay > lastSpendingDay)` – is met, but that value keeps decreasing during the day.
However in the `transferCollateralAsset` that value is local and initialized at 0 and *is not cached* between runs, which means that `pendingLimitForThisAsset == 0` for most invocations of that functions, expect for when the condition is met – `(currentDay > collateralAssetLastSpendingDay[collateralAsset])` – at which point the limit is *temporarily* reset to the value it should have for the next day, but only for that transaction, then it will be `0` until the next day comes.

2023-01-27 17:48 UTC, bayological commented on contracts/Reserve.sol
> +    uint256 spendingLimitForThisAsset = 0;
Will resolve in this PR too

2023-01-31 10:16 UTC, bowd approved these changes
🙏 BOSS 🇧🇦 🐗 🛥️

2023-01-31 14:33 UTC, merged