fix: visibility warnings
mento-protocol/mento-core pull request #124
Opened 2023-01-27 16:29 UTC by ninocomputer

### Description

_A few sentences describing the overall effects and goals of the pull request's commits.
What is the current behavior, and what is the updated/expected behavior with this PR?_

### Other changes

_Describe any minor or "drive-by" changes here._

### Tested

_An explanation of how the changes were tested or an explanation as to why they don't need to be._

### Related issues

- Fixes #[issue number here]

### Backwards compatibility

_Brief explanation of why these changes are/are not backwards compatible._

### Documentation

_The set of community facing docs that have been added/modified because of this change_

2023-01-27 17:08 UTC, bowd requested changes

2023-01-27 17:08 UTC, bowd commented on README.md
> +If you want to ignore a slither warning run: (press enter to get a numbered list of warnings and keep pressing it till it gets to desired section)
Or you can run it with `--detector <your detector>` to not have to triage through all of the issues.

2023-01-27 17:08 UTC, bowd commented on contracts/common/UsingPrecompiles.sol
> -    bytes memory blsKey,
We can't actually make any changes to the `UsingPrecompiles` contract, because most of the core contracts extend it, therefore changing it results in bytecode changes for ALL core contracts. So we're fine to ignore these.

2023-01-30 11:46 UTC, ninocomputer commented on contracts/common/UsingPrecompiles.sol
> -    bytes memory blsKey,
reverted changes

2023-01-30 11:46 UTC, ninocomputer commented on README.md
> +If you want to ignore a slither warning run: (press enter to get a numbered list of warnings and keep pressing it till it gets to desired section)
👍🏼

2023-01-30 12:36 UTC, philbow61 approved these changes
LGTM but what happened to the changes in the readme that you mentioned?

2023-01-30 12:55 UTC, ninocomputer commented
> 

Thanks for the review @philbow61, read Bogdan's review comments for context about why I reverted changes

2023-01-30 14:00 UTC, merged