Fork tests
mento-protocol/mento-core pull request #151
Opened 2023-02-15 19:23 UTC by bowd

### Description

Introduce a class of tests that are designed to run on top of a fork of the mento protocol.
The tests are designed under the assumption that they can run on top of the current state of a live system, so it doesn't make any assumptions or does any setup. It verifies that the invariants of the system hold.

This PR tackles only basic swaps and trading limits from the Issue #144
- [x] Swaps on all of the pools can happen in both directions and the price is in +/-5% of the oracle price.
- [x] Trading limits are configured for each pool
- [x] Trading limits are correctly enforced on all pools in both directions
- [x] Trading limits reset after the correct amount of time and trading resumes

Circuit breaker tests will be added in a subsequent PR.

> Tho' the intent is to not configure the system, the PR currently sets trading limits because they weren't added to the first Baklava deployment, so they are temporarily added here in order to test the test the test.

### Other changes

- Modified remappings.txt to make the Solidity vscode extension happy
- Added the Chain.sol from mento-deployment to this repo as well for the fork tests (in the future we might want to have a mento-libs repo for shared logic but for now it's fine to duplicate these as they are test/deployment utils)
- Modified the TokenHelper to have a generic mint method. 

### Tested

Tested on top of Baklava but with manually configured trading limits.

### Related issues

- Fixes  #144 (Partly)

### Backwards compatibility

All good.

### Documentation

All good.

2023-02-16 22:53 UTC, bayological commented on test/fork-tests/TestAsserts.t.sol
> +  bool __swapAssertDebug = false;
What is the purpose of this flag?

2023-02-17 00:19 UTC, bayological approved these changes
This looks good to me. Nice work 💪.

One thing that would be nice to have, is commands that allow us to run tests for each environment. Currently I need to pass in the profile as an env var when running `forge test --match-contract Baklava`. It would be nice to run a command such as `yarn fork-test:baklava` instead. WDYT?

2023-02-17 04:07 UTC, bowd commented on test/fork-tests/TestAsserts.t.sol
> +  bool __swapAssertDebug = false;
Will remove it. At some point, I wanted to limit the console.log depending on this flag, but in the end, I realized it didn't really make sense to do that and simply rely on the `verbose` flags in the command to control that.

2023-02-17 04:11 UTC, bowd commented
> This looks good to me. Nice work 💪.
> 
> One thing that would be nice to have, is commands that allow us to run tests for each environment. Currently I need to pass in the profile as an env var when running `forge test --match-contract Baklava`. It would be nice to run a command such as `yarn fork-test:baklava` instead. WDYT?

I like 👍 added those in package.json.

2023-02-17 12:40 UTC, nvtaveras requested changes

2023-02-17 12:40 UTC, nvtaveras commented on test/fork-tests/TestAsserts.t.sol
> +    IERC20Metadata(from).approve(address(ctx.broker), sellAmount);
`ctx.broker.swapIn` already mints + approves so no need to do it here?

2023-02-17 12:40 UTC, nvtaveras commented on test/fork-tests/TestAsserts.t.sol
> +    IERC20Metadata(from).approve(address(ctx.broker), maxAmountIn);
ditto `ctx.broker.swapOut`

2023-02-17 12:40 UTC, nvtaveras commented on test/fork-tests/TestAsserts.t.sol
> +    // Always only one limit on a pair
do we want to assert that this is true in `test_tradingLimitsAreConfigured`?

2023-02-17 12:40 UTC, nvtaveras commented on test/fork-tests/TestAsserts.t.sol
> +    console.logInt(maxPossible);
nit: merge to one line?

2023-02-17 12:40 UTC, nvtaveras commented on test/fork-tests/TestAsserts.t.sol
> +    console.logInt(maxPossible);
ditto: merge to one line?

2023-02-17 12:40 UTC, nvtaveras commented on test/fork-tests/TestAsserts.t.sol
> +    TradingLimits.State memory limitState = ctx.tradingLimitsState(to).update(limitConfig, 0, 0);
use `ctx.refreshedTradingLimitsState(to)`?

2023-02-17 12:40 UTC, nvtaveras commented on test/fork-tests/TestAsserts.t.sol
> +    TradingLimits.State memory limitState = ctx.tradingLimitsState(to).update(limitConfig, 0, 0);
ditto use `ctx.refreshedTradingLimitsState(to)`?

2023-02-17 12:40 UTC, nvtaveras commented on test/fork-tests/TestAsserts.t.sol
> +      limitState = ctx.tradingLimitsState(to).update(limitConfig, 0, 0);
do `limitState = ctx.tradingLimitsState(to)`?

2023-02-17 12:40 UTC, nvtaveras commented on test/fork-tests/TestAsserts.t.sol
> +        limitState = ctx.tradingLimitsState(to).update(limitConfig, 0, 0);
do `limitState = ctx.tradingLimitsState(to)`?

2023-02-17 12:40 UTC, nvtaveras commented on test/fork-tests/TestAsserts.t.sol
> +        limitState = ctx.tradingLimitsState(to).update(limitConfig, 0, 0);
do `limitState = ctx.tradingLimitsState(to)`?

2023-02-17 12:40 UTC, nvtaveras commented on test/fork-tests/TestAsserts.t.sol
> +    TradingLimits.State memory limitState = ctx.tradingLimitsState(to).update(limitConfig, 0, 0);
ditto use `ctx.refreshedTradingLimitsState(to)`?

2023-02-17 13:32 UTC, nvtaveras commented on test/fork-tests/TestAsserts.t.sol
> +    console.logInt(maxPossible);
added revert to check is not negative

2023-02-17 13:32 UTC, nvtaveras commented on test/fork-tests/TestAsserts.t.sol
> +    console.logInt(maxPossible);
added revert to check is not negative

2023-02-17 15:41 UTC, nvtaveras commented
LGTM 🚀

2023-02-17 15:49 UTC, nvtaveras approved these changes

2023-02-20 10:38 UTC, merged