Test/no reinitialization
mento-protocol/mento-core pull request #178
Opened 2023-03-31 13:52 UTC by ninocomputer

### Description

_A few sentences describing the overall effects and goals of the pull request's commits.
What is the current behavior, and what is the updated/expected behavior with this PR?_

### Other changes

_Describe any minor or "drive-by" changes here._

### Tested

_An explanation of how the changes were tested or an explanation as to why they don't need to be._

### Related issues

- Fixes #[issue number here]

### Backwards compatibility

_Brief explanation of why these changes are/are not backwards compatible._

### Documentation

_The set of community facing docs that have been added/modified because of this change_

  function test_contractsCanNotBeReinitialized() public {
      BiPoolManager biPoolManager = BiPoolManager(broker.getExchangeProviders()[0]);
      StableToken stableToken = StableToken(registry.getAddressForStringOrDie("StableToken"));
      StableTokenEUR stableTokenEUR = StableTokenEUR(registry.getAddressForStringOrDie("StableTokenEUR"));
      StableTokenEUR stableTokenBRL = StableTokenEUR(registry.getAddressForStringOrDie("StableTokenBRL"));

      vm.expectRevert("contract already initialized");
      broker.initialize(new address[](0), address(reserve));

      vm.expectRevert("contract already initialized");
      biPoolManager.initialize(address(broker), reserve, sortedOracles, breakerBox);

      vm.expectRevert("contract already initialized");
      breakerBox.initialize(new address[](0), sortedOracles);

      vm.expectRevert("contract already initialized");
      sortedOracles.initialize(1);

      vm.expectRevert("contract already initialized");
      reserve.initialize(address(10),0 ,0 ,0 ,0 , new bytes32[](0), new uint256[](0), 0, 0, new address[](0), new uint256[](0));

      vm.expectRevert("contract already initialized");
      stableToken.initialize("", "", 8, address(10), 0, 0, new address[](0), new uint256[](0), "");

      vm.expectRevert("contract already initialized");
      stableTokenEUR.initialize("", "", 8, address(10), 0, 0, new address[](0), new uint256[](0), "");

      vm.expectRevert("contract already initialized");
      stableTokenBRL.initialize("", "", 8, address(10), 0, 0, new address[](0), new uint256[](0), "");
  }

2023-03-31 14:13 UTC, ninocomputer commented on slither.db.json
Ignored the error about using 5.0.13 in production

2023-03-31 14:55 UTC, bayological requested changes

2023-03-31 14:55 UTC, bayological commented on test/fork-tests/BaseForkTest.t.sol
> +  function test_contractsCanNotBeReinitialized() public {
Separate this into smaller test functions that focus on the initialization of one contract. This will make it easier to identify which contract initialization test case has failed, especially as the revert messages are all the same.

2023-04-03 10:15 UTC, tobikuhlmann approved these changes
looks good to me

2023-04-03 21:41 UTC, bayological approved these changes

2023-04-04 08:04 UTC, merged