Update the StableToken implementation to a modern ERC20 (Solidity 0.8.19)
mento-protocol/mento-core pull request #193
Opened 2023-05-19 09:59 UTC by bowd

### Description

_A few sentences describing the overall effects and goals of the pull request's commits.
What is the current behavior, and what is the updated/expected behavior with this PR?_

### Other changes

_Describe any minor or "drive-by" changes here._

### Tested

_An explanation of how the changes were tested or an explanation as to why they don't need to be._

### Related issues

- Fixes #[issue number here]

### Backwards compatibility

_Brief explanation of why these changes are/are not backwards compatible._

### Documentation

_The set of community facing docs that have been added/modified because of this change_

2023-05-31 17:33 UTC, bayological requested changes
All looks fine to me. Left some comments on naming and comments.

2023-05-31 17:33 UTC, bayological commented on test/legacy/Exchange.t.sol
> +    stableToken = IStableTokenV2(factory.create("StableTokenV2", abi.encode(false)));
Why are we initializing the stableToken this way? Is this a workaround for the Solidity version?

2023-05-31 17:33 UTC, bayological commented on test/utils/Factory.sol
> +contract Factory {
A dev comment on why this should be used would be helpful.

2023-05-31 17:33 UTC, bayological commented on test/tokens/StableTokenV2.t.sol
> +  function test_initializers_disabled() public {
Let's stick to the naming convention for these tests, it adds more context and makes it easier to identify the intention of the test and expected result at a glance.
![image](https://github.com/mento-protocol/mento-core/assets/6872903/c07e651e-6445-401c-9cc0-554c1b7c4cf1)
vs
![image](https://github.com/mento-protocol/mento-core/assets/6872903/c9f34351-bc7c-4960-9100-954d64eb1052)

2023-05-31 17:33 UTC, bayological requested changes
All looks fine to me. Left some comments on naming and comments.

2023-05-31 17:37 UTC, bayological commented on test/legacy/Exchange.t.sol
> +    stableToken = IStableTokenV2(factory.create("StableTokenV2", abi.encode(false)));
Sorry, I've just seen the note on the PR. 👍🏿

2023-06-01 21:52 UTC, bayological approved these changes

2023-06-02 13:00 UTC, ninocomputer approved these changes

2023-06-02 13:00 UTC, ninocomputer approved these changes

2023-06-23 11:59 UTC, nvtaveras approved these changes
🚀 🌑

2023-06-23 13:22 UTC, merged