Feature/refactor breaker box
mento-protocol/mento-core pull request #201
Opened 2023-06-05 15:37 UTC by philbow61

### Description

- This pr refactors the BreakerBox to support multiple dependent breakers for a rate feed.
- in addition to those changes mentioned in the acceptance criteria I also removed the breakerEnabled mapping since it follows the structure of the new breakerStatus mapping and therefore can be added to the breaker Status struct.
- I use the address(0) breaker to quickly and efficiently track whether a rateFeed is included in the breakerStatus mapping.

### Other changes

- had to update the testAssert as it was dependent on the old mappings in order to get everything to compile
- the only problem with this is that the fork tests fail since the old version is deployed/ used 

### Tested

- updated the BreakerBox tests and added new tests for the changed logic 

### Related issues

- Fixes #196

### Backwards compatibility

- N/A

### Documentation

- N/A

2023-06-09 01:59 UTC, bayological requested changes

2023-06-09 01:59 UTC, bayological commented on contracts/BreakerBox.sol
>    // Maps a breaker to the associated trading mode.
Just for more clarity.
```suggestion 
  // Maps a breaker to the associated trading mode it should activate when triggered.
```

2023-06-09 01:59 UTC, bayological commented on contracts/BreakerBox.sol
> +  mapping(address => mapping(address => BreakerStatus)) public breakerStatus;
I would consider renaming this to rateFeedBreakerStatus for clarity and consistency.

2023-06-12 09:38 UTC, nvtaveras requested changes
Requesting mostly small changes, it looks great overall!

2023-06-12 09:38 UTC, nvtaveras commented on contracts/BreakerBox.sol
> +    } else return checkBreaker(rateFeedID, breaker);
no need for the else statement here. also, what happened to your curly brackets in the `else` statements? 😅

2023-06-12 09:38 UTC, nvtaveras commented on contracts/BreakerBox.sol
> +    } else emit ResetAttemptNotCool(rateFeedID, _breaker);
can you add both opening and closing brackets for all the else statements?

2023-06-12 09:38 UTC, nvtaveras commented on contracts/BreakerBox.sol
> +    if ((cooldown > 0) && (cooldown.add(_breakerStatus.lastUpdatedTime) <= block.timestamp)) {
I think it'd be good to keep this comment from the old code:
`// If the cooldown == 0, then a manual reset is required.`.

Also, I always found `(cooldown.add(_breakerStatus.lastUpdatedTime) <= block.timestamp)` more confusing than `now >= cooldown + lastUpdatedTime`. Not sure if others agree, if yes then maybe we can change it?

2023-06-12 09:38 UTC, nvtaveras commented on contracts/BreakerBox.sol
> +    breakers.pop();
this logic looks fine to me, but I didn't see unit tests for calling this function when there's more than one breaker?

2023-06-12 10:48 UTC, philbow61 commented on contracts/BreakerBox.sol
>      address[] memory activeRateFeeds = rateFeedIDs;
I think we can't set the trading mode of all RateFeeds using the breaker to the default trading mode because there could be additional breakers active for that rate feed that are not in the default trading mode.

2023-06-12 11:05 UTC, philbow61 commented on contracts/BreakerBox.sol
> +    if ((cooldown > 0) && (cooldown.add(_breakerStatus.lastUpdatedTime) <= block.timestamp)) {
i agree 🤝

2023-06-13 02:17 UTC, bayological approved these changes

2023-06-13 12:50 UTC, nvtaveras requested changes

2023-06-13 13:02 UTC, nvtaveras approved these changes
great work! 🚀 🚀 🚀 🚢 🚢 🚢

2023-06-13 13:08 UTC, merged