feat: value based constant sum pricing module
mento-protocol/mento-core pull request #210
Opened 2023-06-16 16:35 UTC by philbow61

### Description

This PR changes the implementation of the constant sum pricing module from token amount constant sum to value-based constant sum. This is achieved by taking the bucket ration as a conversion rate 
`X = TokenInBucketSize`
`Y = TokenOutBucketSize`
`x = amountIn`
`y = amountOut`
`base Formula: (X + x*(1-spread)) * p + Y - y = K`
`with p: Y/X`

`Formula getAmountOut: amountOut = (1 - spread) * amountIn * tokenOutBucketSize) / tokenInBucketSize`
`Formula getAmountIn: amountIn = (amountOut  * tokenInBucketSize) / (tokenOutBucketSize * (1 - spread))`

### Other changes

- N/A 

### Tested

wrote new Test but will reach out to Nadiem for additional verification 

### Related issues

- Fixes #206 

### Backwards compatibility

### Documentation

2023-06-20 14:40 UTC, ninocomputer requested changes
just nits

2023-06-22 08:20 UTC, ninocomputer requested changes

2023-06-22 08:20 UTC, ninocomputer commented on contracts/ConstantSumPricingModule.sol
> +   * @param tokenInBucketSize The bucket size of the token swapt in.
```suggestion
   * @param tokenInBucketSize The bucket size of the token swapped in.
```

2023-06-22 08:20 UTC, ninocomputer commented on contracts/ConstantSumPricingModule.sol
>     * @param tokenOutBucketSize The bucket size of the token swapt out.
```suggestion
   * @param tokenOutBucketSize The bucket size of the token swapped out.
```

2023-06-22 08:20 UTC, ninocomputer commented on contracts/ConstantSumPricingModule.sol
>     * @param amountOut The amount of tokens in wei that should be swapt out.
```suggestion
   * @param amountOut The amount of tokens in wei that should be swapped out.
```

2023-06-22 08:20 UTC, ninocomputer commented on contracts/ConstantSumPricingModule.sol
>     * @param tokenOutBucketSize The bucket size of the token swapt out.
```suggestion
   * @param tokenOutBucketSize The bucket size of the token swapped out.
```

2023-06-29 12:27 UTC, sissnad commented
Are we testing 1 Wei amount swaps somewhere. I think it would make sense to have it for every pricing module.
1. Price: 2 InAmount: 1 Wei => OutAmount: 0 Wei
2. Price: 0.5 InAmount: 1 Wei => OutAmount: 1 Wei

2023-06-29 14:11 UTC, philbow61 commented
> Are we testing 1 Wei amount swaps somewhere? I think it would make sense to have this test for every pricing module not only constantSum.
> 
> 1. Price: 2, InAmount: 1 Wei => OutAmount: 0 Wei
> 2. Price: 0.5, InAmount: 1 Wei => OutAmount: 1 Wei

shouldn't it be 
2. Price: 0.5, InAmount: 1 Wei => OutAmount: 1/0.5 = 2 Wei

2023-06-29 15:46 UTC, sissnad commented
You right @philbow61. Was a typo

2023-06-30 15:32 UTC, philbow61 commented on test/swap/BiPoolManager.t.sol
> +    sortedOracles.setOldestReportExpired(USDUSDC_rateFeedID);
In the unit tests the minimum reports were set explicitly in the pool creation based on what is supposed to be tested. 
Most of the time 0 is used in other cases where the value is essential for the test case it is set to 5.
The same goes for the number of reports. Also, we are using a mock sorted oracles contract here where we can e.g explicitly define the return value of `sortedOracles.isOldestReportExpired()` independent of any rates.

Similar test scenarios are also tested in the ConstantSumIntegrationTests. Here we are using the actual contracts no mocks. Here the pools are created with `minimumReports = 5;` and ten reports are submitted to the sortedOracles contract. Those are then manipulated(e.g) for specific scenarios like `sortedOracles.numRates()` or `sortedOracles.isOldestReportExpired()`

2023-06-30 15:53 UTC, bowd commented on contracts/swap/BiPoolManager.sol
> +    bool hasUsableMedian = oracleHasUsableMedian(exchange);
Let's go for "valid"

2023-06-30 15:53 UTC, bowd commented on test/integration/ConstantSumIntegration.t.sol
> +  function test_swap_whenConstantSum_pricesShouldStayTheSameInBetweenBucketUpdates() public {
Should we also test cEUR/USDC? Feels like when the oracle price is not `1` is also an important integration test.

2023-06-30 16:31 UTC, sissnad commented on test/integration/ConstantSumIntegration.t.sol
> +  function test_swap_whenConstantSum_pricesShouldStayTheSameInBetweenBucketUpdates() public {
Yes, I agree that's important. It is happening as part of the 1 Wei amount test I suggested above. But does not harm to have an individual test case

2023-07-03 10:32 UTC, sissnad commented on test/integration/ConstantSumIntegration.t.sol
> +  function test_swap_whenConstantSum_pricesShouldStayTheSameInBetweenBucketUpdates() public {
I think this test also test swaps at prices `!= 1` [test_swap_whenConstantSum_pricesShouldChangeWhenBucketRatioChanges()](https://github.com/mento-protocol/mento-core/blob/5aac8af27487b8298a69b6928576d00102296754/test/integration/ConstantSumIntegration.t.sol#L100)

2023-07-03 10:48 UTC, sissnad commented on test/integration/ConstantSumIntegration.t.sol
> +  function test_swap_whenConstantSum_pricesShouldStayTheSameInBetweenBucketUpdates() public {
What might be interesting as well is going through all tests and check their assumptions. Whereever we assume `price = 1` and/or `cUSDUSDC` 

- we can either replace assumption like `price = 1` and/or `cUSDUSDC` by a `price !=1` and `cEURUSDC`   

- or loop through `[1, 3.7]` and `cEURUSDC`. 

That way we make sure we are not performing the tests for the special case `price = 1 only

2023-07-04 08:34 UTC, sissnad requested changes
Either `test_swap_whenCircuitBreakerActivates_shouldDisableTrading()`in `BrokerIntegration.t.sol` should be extended to cover all relevant cases in which trading is disabled. Or we should setup unit tests or lower level integratiton tests that make sure the breaker sets the trading mode correctly in all cases and test then test that broker reacts correctly to the tradinbg mode for all exchanges.

2023-07-05 13:47 UTC, ninocomputer approved these changes
overall, it looks good to me! Contract changes make sense and the tests seem comprehensive.

2023-07-05 13:52 UTC, sissnad approved these changes
With breaker and constant sum related integration tests being covered by #219 looks good to me!

2023-07-05 15:33 UTC, bowd requested changes
Great work! 🎉 🎉 , made some suggestions to improve the readability a bit here and there.

2023-07-05 15:33 UTC, bowd commented on contracts/swap/BiPoolManager.sol
>    }
I would rewrite this like so:

```solidity
if (isConstantProduct) {
  if (tokenIn = exchange.asset0) {
    exchange.bucket0 = exchange.bucket0.add(amountIn);
    exchange.bucket1 = exchange.bucket1.sub(amountOut);
  } else {
    // reverse
  }
}

exchange[exchangeId].bucket0 = exchange.bucket0;
exchange[exchangeId].bucket1 = exchange.bucket1;
if (bucketsUpdated) {
  exchange[exchangeId].lastBucketUpdate = now;
  emit BucketsUpdated(...);
}


```

I think it's a bit clearer and I would add a `@dev` comment in the documentation of the function that explains why we only change the buckets with the amounts when it uses constant product.

2023-07-05 15:33 UTC, bowd commented on contracts/swap/BiPoolManager.sol
> +    if (keccak256(abi.encodePacked(exchange.pricingModule.name())) == CONSTANT_SUM) {
I'm thinking we should add an internal function for this:
```solidity
function pricingModuleIdentifier(PoolExchange memory exchange) internal pure returns (bytes32) {
  return keccak256(abi.encodePacked(exchange.pricingModule.name()));
}

function isConstantSum(PoolExchange memory exchange) internal pure returns (bool) {
  return pricingModuleIdentifier(exchange) == CONSTANT_SUM
}

function isConstantProduct(PoolExchange memory exchange) internal pure returns (bool) {
  return pricingModuleIdentifier(exchange) == CONSTANT_PRODUCT
}
```

From my understanding of how `internal` functions work this shouldn't result in any difference to the bytecode as all internal functions are inlined and it doesn't result in function execution or stacks or anything, but I've never actually looked at the bytecode and I'm quite curious now so I might take a look, either way I'd make this a bit more readable.

2023-07-05 15:33 UTC, bowd commented on test/swap/ConstantSumPricingModule.t.sol
> +    assertEq(amountIn, (amountOut * 1) / 2);
Is there a reason you're using the multiplication identity operator here? 😂

2023-07-06 10:17 UTC, merged