Test/breaker integration
mento-protocol/mento-core pull request #226
Opened 2023-07-14 20:43 UTC by ninocomputer

### Description

_A few sentences describing the overall effects and goals of the pull request's commits.
What is the current behavior, and what is the updated/expected behavior with this PR?_

### Other changes

_Describe any minor or "drive-by" changes here._

### Tested

_An explanation of how the changes were tested or an explanation as to why they don't need to be._

### Related issues

- Fixes #[issue number here]

### Backwards compatibility

_Brief explanation of why these changes are/are not backwards compatible._

### Documentation

_The set of community facing docs that have been added/modified because of this change_

2023-07-31 12:01 UTC, bowd commented on test/integration/CircuitBreakerIntegration.t.sol
> +    vm.warp(now + 5 minutes);
This doesn't actually test what's expected, we need to also do a `setMedianRate` again with a value that still exceeds in order to actually execute the logic that could result in a cooldown, otherwise here you're just validating that the trading mode hasn't changed after 5 minutes without executing any action that could change it.

2023-07-31 12:01 UTC, bowd commented on test/integration/CircuitBreakerIntegration.t.sol
> +    vm.warp(now + 1 seconds);
Ditto

2023-08-01 13:53 UTC, ninocomputer commented on test/integration/CircuitBreakerIntegration.t.sol
> +    vm.warp(now + 5 minutes);
👍🏼

2023-08-01 13:53 UTC, ninocomputer commented on test/integration/CircuitBreakerIntegration.t.sol
> +    setMedianRate(cUSD_bridgedUSDC_referenceRateFeedID, 1e24 + 1e24 * 0.11);
added 2 more tests for it

2023-08-01 14:26 UTC, bowd approved these changes

2023-08-01 21:55 UTC, bayological requested changes

2023-08-01 21:55 UTC, bayological commented on test/integration/CircuitBreakerIntegration.t.sol
> +    // console.log(5e23 - 5e23 * 0.151, "new threshold");
Let's get this removed.

2023-08-01 21:55 UTC, bayological commented on test/integration/CircuitBreakerIntegration.t.sol
These are good. We should add a test to verify the manual reset logic also, so with both breakers simulate when the breaker has been triggered for rate feeds with 0 cooldown.

2023-08-01 21:55 UTC, bayological commented on test/integration/CircuitBreakerIntegration.t.sol
> +    assertEq(blockNumber, block.number); // block number should not change
Why is this assertion needed? In the tests there is no manipulation of the state that would advance the block number.

2023-08-01 21:55 UTC, bayological commented on test/integration/CircuitBreakerIntegration.t.sol
> +    assertEq(blockNumber, block.number); // block number should not change
Same as above, why is this needed?

2023-08-02 11:56 UTC, philbow61 commented on test/integration/CircuitBreakerIntegration.t.sol
> +    assertEq(blockNumber, block.number); // block number should not change
Yeah, we also didn't like this while writing it. Essentially one of the requirements was to test that the behavior of breaking and recovering works correctly when all happens in the same block.

2023-08-02 16:01 UTC, bayological approved these changes

2023-08-02 16:03 UTC, merged