fix:validate token precision multiplier
mento-protocol/mento-core pull request #241
Opened 2023-08-02 23:31 UTC by bayological

### Description

This change adds validation to the function `BiPoolManager.setTokenPrecisionMultipliers` similar to that in the create pool function. The change verifies the tokens being added to the mapping are known by the reserve and the precisions are within the allowed range.

### Other changes

- N/A

### Tested

- Unit tests were added to verify the change functions as expected.

### Related issues

- Closes #238 

### Backwards compatibility

- N/A

### Documentation

- N/A

2023-08-03 21:38 UTC, philbow61 requested changes
LGTM if we want to go down this route 👍 
I personally would argue there is no need for the setTokenPrecisionMultipliers function in the beginning. 
They are automatically set in the createExchange function by calling decimals() on the token contract. The only context where these multipliers are used is in quotes/swaps and those only work on a valid exchange. So what is the use case for this function in my opinion it can only cause problems by setting wrong values, but maybe I am missing something 😁

2023-08-04 03:56 UTC, bayological commented
> LGTM if we want to go down this route 👍 I personally would argue there is no need for the setTokenPrecisionMultipliers function in the beginning. They are automatically set in the createExchange function by calling decimals() on the token contract. The only context where these multipliers are used is in quotes/swaps and those only work on a valid exchanges. So what is the use case for this function in my opinion it can only cause problems by setting wrong values, but maybe I am missing something grin

I agree with you. I don't feel strongly about keeping this function, it does not add much. However, there is no harm in having it there 🤷‍♂️. The only use case that comes to mind is if the multiplier was set incorrectly when creating an exchange, this would allow that to be corrected without recreating the exchange.

2023-08-07 10:07 UTC, philbow61 approved these changes
🔥

2023-08-07 10:19 UTC, ninocomputer approved these changes

2023-08-07 10:20 UTC, merged