feat: verify pricing modules
mento-protocol/mento-core pull request #242
Opened 2023-08-03 01:30 UTC by bayological

### Description

This change adds validation of the pricing module used for exchange creation in `BiPoolManager.createExchange`.

### Other changes

- Added protected setter function to update the mapping with allowed pricing modules.
- Added call to set pricing modules in integration tests.

### Tested

- Added unit tests to verify functionality works as expected.

### Related issues

- Closes #239 

### Backwards compatibility

- N/A

### Documentation

- N/A

2023-08-03 22:10 UTC, philbow61 approved these changes
LGTM 🛥️

2023-08-09 08:56 UTC, ninocomputer requested changes

2023-08-09 08:56 UTC, ninocomputer commented on contracts/swap/BiPoolManager.sol
> +  function setPricingModules(bytes32[] calldata identifiers, address[] calldata modules) external onlyOwner {
I don't think just `identifiers` is clear enough maybe I'd change it to `pricingModuleIDs`

2023-08-09 12:39 UTC, ninocomputer approved these changes

2023-08-09 12:39 UTC, philbow61 commented on contracts/swap/BiPoolManager.sol
> +  function setPricingModules(bytes32[] calldata identifiers, address[] calldata modules) external onlyOwner {
we decided on not to rename this

2023-08-09 13:11 UTC, merged