Feature/add missing access controls
mento-protocol/mento-core pull request #259
Opened 2023-08-07 10:00 UTC by ninocomputer

### Description

_A few sentences describing the overall effects and goals of the pull request's commits.
What is the current behavior, and what is the updated/expected behavior with this PR?_

### Other changes

_Describe any minor or "drive-by" changes here._

### Tested

_An explanation of how the changes were tested or an explanation as to why they don't need to be._

### Related issues

- Fixes #[issue number here]

### Backwards compatibility

_Brief explanation of why these changes are/are not backwards compatible._

### Documentation

_The set of community facing docs that have been added/modified because of this change_

2023-08-07 11:53 UTC, philbow61 requested changes
I think you need to change more that this. The shouldTrigger() function is called as part of the checkAndSetBreaker call in the BreakerBox. Since this function is still public you could still initiate the call to shouldTrigger via a call to checkAndSetBreakers

2023-08-07 11:53 UTC, philbow61 commented on contracts/oracles/breakers/MedianDeltaBreaker.sol
> +    require(msg.sender == breakerBox, "Caller must be the BreakerBox contract");
can we move this into a modifier onlyBreakerBox

2023-08-07 11:55 UTC, ninocomputer commented on contracts/oracles/breakers/MedianDeltaBreaker.sol
> +    require(msg.sender == breakerBox, "Caller must be the BreakerBox contract");
I wouldn't add a modifier because we're using this check only in one place.

2023-08-08 11:29 UTC, bowd requested changes

2023-08-08 11:29 UTC, bowd commented on contracts/oracles/BreakerBox.sol
> +
I think on the current state of the PR there's no internal call of this function, but it will be when @philbow61 's other PR is merged. I would say to wait for that to be merged and then refactor this a bit into an external `checkAndSetBreakers` which verifies msg.sender, and an internal `_checkAndSetBreakers` which doesn't verify msg.sender, and is the one also called internally.

2023-08-08 11:29 UTC, bowd commented on contracts/swap/BiPoolManager.sol
> +    tokenPrecisionMultipliers[exchange.asset1] = 10**(18 - uint256(IERC20Metadata(exchange.asset1).decimals()));
Why did you change this here? It's more inefficient to call the `decimals()` view function two times here.

2023-08-10 10:02 UTC, bowd approved these changes

2023-08-10 10:22 UTC, merged