feat: use return values in the function declaration
mento-protocol/mento-core pull request #263
Opened 2023-08-11 15:14 UTC by ninocomputer

### Description

Use return values in the function declaration

### Other changes

n/a

### Tested

n/a

### Related issues

- Fixes #250 

### Backwards compatibility

n/a

### Documentation

n/a

2023-08-11 15:22 UTC, bowd requested changes

2023-08-11 15:22 UTC, bowd commented on contracts/swap/BiPoolManager.sol
>      return (rateNumerator, rateDenominator);
Remove this line

2023-08-11 15:50 UTC, philbow61 approved these changes

2023-08-12 17:27 UTC, bowd approved these changes

2023-08-14 08:02 UTC, merged