Feat: Mint function for emission contract
mento-protocol/mento-core pull request #267
Opened 2023-09-08 08:13 UTC by baroooo

### Description

Instead of pre-minting 100% of the supply, token contract enables emission contract to mint 65% of the total supply.

### Other changes

None

### Tested

Changes are tested with unit tests

### Related issues

- Fixes #305

### Backwards compatibility

N/A

### Documentation

N/A

2023-09-12 09:25 UTC, philbow61 requested changes

2023-09-12 09:25 UTC, philbow61 commented on contracts/governance/MentoToken.sol
> +    address emissionContract_
out of interest why the underscore behind the variable name instead of before 🤔 ? 
In other constructors we used the underscore before so maybe for consistency I would stick to that.

2023-09-12 09:25 UTC, philbow61 commented on contracts/governance/MentoToken.sol
> +    require(msg.sender == emissionContract, "MentoToken: OnlyEmissionContract");
Maybe we can make the revert messages a bit more human-readable and not use CamelCase. I don't have a strong opinion on that, but I would probably do it to be more consistent with other mento contracts.

2023-09-12 09:25 UTC, philbow61 commented on test/governance/MentoToken.t.sol
> +  function test_mint_shouldRevert_forAmountsBiggerThanSupply() public {
```suggestion
  function test_mint_shouldRevert_forAmountsBiggerThanEmissionSupply() public {
```

2023-09-12 09:30 UTC, philbow61 reviewed
I think in the past we tried following a different test naming convention:
test_"FunctionToTest"_when"StateToTest"_should"ExpectedBehavior".
Although we did not follow this convention completely, it may be helpful to refactor some test names to align with it.

2023-09-12 09:52 UTC, baroooo commented on contracts/governance/MentoToken.sol
> +    address emissionContract_
this is by solidity stye guide: https://docs.soliditylang.org/en/v0.8.19/style-guide.html#avoiding-naming-collisions
it avoids the name collision and also signals emission contract will be treated differently.

by the same convention, prefixed underscore should be used for non-external state vars and not params: https://docs.soliditylang.org/en/v0.8.19/style-guide.html#underscore-prefix-for-non-external-functions-and-variables

having said that, it is just a convention and we can stick to the old way

2023-09-12 10:24 UTC, philbow61 approved these changes
LGTM 👍

2023-09-12 10:25 UTC, philbow61 commented on contracts/governance/MentoToken.sol
> +    address emissionContract_
seeing this i would say it looks good 👍

2023-09-13 14:41 UTC, nvtaveras approved these changes
🚢

2023-09-13 14:42 UTC, merged