Migrate StableToken tests
mento-protocol/mento-core pull request #27
Opened 2022-10-18 10:49 UTC by ninocomputer

### Description

2022-10-28 12:59 UTC, philbow61 reviewed
All in all looks good to me :) I left some comments where I felt unsure. Hope maybe @bayological or @bowd  can take a look at it as well

2022-10-28 12:59 UTC, philbow61 commented on test/StableToken.t.sol
> +
Enjoyed the following part with the mintAndAssert function😎

2022-10-28 12:59 UTC, philbow61 commented on test/StableToken.t.sol
> +    assertEq(adjustedBalance, 1e20);
shouldn't the balance change based on the set inflationRate? 
Not sure if I understood everything right 😌

2022-10-28 12:59 UTC, philbow61 commented on test/StableToken.t.sol
> +
Enjoyed the following part with the burnAndAssert function😎

2022-10-28 12:59 UTC, philbow61 commented on test/StableToken.t.sol
> +
I think here one test from the celo mono-repo is missing  
`allowance() should return allowance`

2022-10-28 12:59 UTC, philbow61 commented on test/StableToken.t.sol
> +
I am unsure about the following part. Don't really understand where these Results come from. The Original tests form the mono-repo seem different, but maybe I am missing something.

2022-10-28 13:46 UTC, ninocomputer commented on test/StableToken.t.sol
> +    vm.expectEmit(false, false, false, true);
yeah, good catch!

2022-10-28 15:09 UTC, ninocomputer commented on test/StableToken.t.sol
> +    assertEq(adjustedBalance, 1e20);
yes, you did understand it right! Time travel is necessary for the inflation factor to update.

2022-10-29 12:05 UTC, bayological commented on test/StableToken.t.sol
> +    vm.expectEmit(false, false, false, true);
@ninocomputer unresolved this, so it's not missed as the params have not been updated yet.

2022-10-29 12:18 UTC, bayological commented
> All in all looks good to me :) I left some comments where I felt unsure. Hope maybe @bayological or @bowd can take a look at it as well

I will look over the comments, but for this PR it makes sense for @bowd to review as I also did some of the tests.

2022-10-31 15:19 UTC, ninocomputer commented on test/StableToken.t.sol
> +
in monorepo in this particular test, I believe inflation factor is 1.005 * 10**24 but here the factor is 0.995 * 10**24 so the result is obviously different for this reason

2022-11-08 07:57 UTC, bowd requested changes
Great job overall! 
There's that complexity with the `fractionMulExp` precompile that I would like us to cover. Let me know if the comment I left makes sense and you know how to approach it.

2022-11-08 07:57 UTC, bowd commented on test/StableToken.t.sol
> +
This is because the mock you set up for `fractionMulExp` doesn't actually calculate the right values.
You can take a look [here](er/packages/vm/lib/evm/precompiles/fc-fractionmulexp.ts) for what the `fractionMulExp` should do. Essentially it's `a * b^exp` where a and b are both fractions, normalized to a number of decimals. So the parameters passed to the precompile are:
- aNumerator
- aDenominator
- bNumerator
- bDenominator
- exponent
- decimals

So the actual mock that you're setting now: 
```solidity
    ph.mockReturn(
      FRACTION_MUL,
      keccak256(abi.encodePacked(uint256(1e24), uint256(1e24), uint256(995e21), uint256(1e24), uint256(1), uint256(18))),
      abi.encode(uint256(100), uint256(12))
    );
``` 
Doesn't make sense for the values.

You have:
a = 1e24 / 1e24
b = 995e21 / 1e24
exp = 1
decimals = 18

Return value should be:
a * b^exp = a * b `(exp = 1)`
a * b = 995e21 / 1e24

And if we normalize for 18 decimals:

resultNumerator = 995e21 * 1e18 / 1e24 = 995e15
resultDenominator = 1e18

So the mock should be:
```solidity
    ph.mockReturn(
      FRACTION_MUL,
      keccak256(abi.encodePacked(uint256(1e24), uint256(1e24), uint256(995e21), uint256(1e24), uint256(1), uint256(18))),
      abi.encode(uint256(995e15), uint256(1e18))
    );
``` 

Then I would suggest replicating the other specs as well with the other inflation factors and time periods (which will result in higher exp values).

I would do this by: 
1.  writing a missing test case
2. running it, which will result in an error because there's no mock registered for that particular call of the precompile
3. look at the output of the failure to extract the arguments for the precompile
4. calculate the correct response using the formulas above
5. add a precompile mock
6. rinse and repeated until there are no more test cases

---

Long term this would be cleaner if the precompile test helpers actually implemented the a*b^exp calculation somehow and there are ways using `ffi` in forge to call to an external script, but that has more complexity and we're looking to move away from inflation anyway which might end up removing all of this code so I would keep it simple now.

2022-11-08 12:21 UTC, ninocomputer commented on test/StableToken.t.sol
> +    comment = "pineapples absolutely do not belong on pizza";
NEVER

2022-11-08 12:39 UTC, ninocomputer commented on test/StableToken.t.sol
> +
yes, yes now looking at the encoded values I realise that initially they were placeholders that I didn't calculate just to get the mock working and forgot to change. Now, this makes sense why the inflation factor was off.

2022-11-08 13:05 UTC, bowd commented on test/StableToken.t.sol
> +
@philbow61 can you pick this up and get this PR across the finish line, so that @ninocomputer can focus on the Circuit Breaker work?

2022-11-08 13:15 UTC, philbow61 commented on test/StableToken.t.sol
> +
sure! I am on it

2022-11-09 12:20 UTC, philbow61 commented on test/StableToken.t.sol
> +
@bowd should be all fixed now. I also added the code for making the broker capable of minting Stabletokens and the corresponding tests.

2022-11-10 06:37 UTC, bowd approved these changes

2022-11-10 06:37 UTC, bowd commented on test/StableToken.t.sol
> +
Awesome! Great job!

2022-11-10 06:39 UTC, merged