Airgrab
mento-protocol/mento-core pull request #274
Opened 2023-09-17 07:28 UTC by bowd

### Description

_A few sentences describing the overall effects and goals of the pull request's commits.
What is the current behavior, and what is the updated/expected behavior with this PR?_

### Other changes

_Describe any minor or "drive-by" changes here._

### Tested

_An explanation of how the changes were tested or an explanation as to why they don't need to be._

### Related issues

- Fixes #[issue number here]

### Backwards compatibility

_Brief explanation of why these changes are/are not backwards compatible._

### Documentation

_The set of community facing docs that have been added/modified because of this change_

2023-10-05 12:55 UTC, philbow61 requested changes
LGTM 🦈 
just some nits / questions

2023-10-05 12:55 UTC, philbow61 commented on contracts/governance/Airgrab.sol
> +  function drain(address tokenToDrain) external nonReentrant {
what is the scenario of draining a different token than the Mento token?

2023-10-05 12:55 UTC, philbow61 commented on test/governance/Airgrab.t.sol
> +  function test_Drain_beforeAirgrabEnds() public d_setUp {
nit:
why are these tests marked as public while others on top are marked as external?

2023-10-05 12:55 UTC, philbow61 commented on test/governance/Airgrab.t.sol
> +  }
nit: 
can we add another assert to verify the allowance was set correctly

2023-10-05 12:55 UTC, philbow61 commented on test/governance/Airgrab.t.sol
> +  /// @notice when the claimer has not enough balance
should it be the Airgrab contract here?
`/// @notice when the Airgrab contract has not enough balance`

2023-10-06 12:20 UTC, baroooo requested changes

2023-10-06 12:20 UTC, baroooo commented on contracts/governance/Airgrab.sol
> +    bytes32 leaf = keccak256(bytes.concat(keccak256(abi.encode(account, uint256(amount)))));
why do we do bytes.concat and second hash here ?

2023-10-06 13:41 UTC, bowd commented on contracts/governance/Airgrab.sol
> +    uint256 votingPower = lockingContract.lock(account, address(0), amount, slopePeriod, cliffPeriod);
Huh I dunno why I thought if your voting power is not delegated than it means you wield it, cool, I'll add delegate configuration at the contract level so we can set from the UI if we want to.

2023-10-06 13:51 UTC, bowd commented on contracts/governance/Airgrab.sol
> +    require(fractalMaxAge == 0 || block.timestamp < approvedAt + fractalMaxAge, "Airgrab: KYC not recent enough");
This is how they suggest setting things up because I think their KYCs have a pretty long `validUntil` but it could be that our own business logic would require us to only accept kyc's with a certain freshness.

2023-10-06 13:57 UTC, baroooo commented on contracts/governance/Airgrab.sol
> +    bytes32 leaf = keccak256(bytes.concat(keccak256(abi.encode(account, uint256(amount)))));
oh ok, looks like it is a recent change made against second preimage attack:
https://flawed.net.nz/2018/02/21/attacking-merkle-trees-with-a-second-preimage-attack/

2023-10-06 13:59 UTC, baroooo commented on contracts/governance/Airgrab.sol
> +    bytes32 leaf = keccak256(bytes.concat(keccak256(abi.encode(account, uint256(amount)))));
I remember a great CTF challenge from paradigm which is related to this if anyone interested:

https://github.com/paradigmxyz/paradigm-ctf-2022/tree/main/merkledrop

2023-10-06 14:36 UTC, bowd commented on contracts/governance/Airgrab.sol
> +  uint32 public constant MAX_CLIFF_PERIOD = 103;
So here's the logic:
4 years is 52 * 4 = 208 weeks
In the locking contract things are at week resolution so say time looks like this with week numbers in parentheses.
```
----(N)-------(N+1)-------(N+2)-------(N+4)--------
           ^ we want to lock here
```

If we select locking for one week, we will actually be snapping to (N) as the start date and have (N+2) as the end date. So, in effect we're locking for ~10 days as if the user started at (N).

So then, if we want the maximum to be 2 years, we actually want to select 2 years - 1 week so max of 207 week, which will effectively result in 208 weeks locking.

@baroooo correct me if I'm wrong here

2023-10-06 15:48 UTC, philbow61 approved these changes

2023-10-06 15:48 UTC, philbow61 commented on contracts/governance/Airgrab.sol
> +   * @dev Allows `account` to claim `amount` tokens if the merkle proof and kyc is valid.
Can we update the comment because of the changes from `account -> msg.sender`

2023-10-06 15:48 UTC, philbow61 commented on test/governance/Airgrab.t.sol
> +  function test_Claim_canClaim_whenInvalidClaimAmount_reverts() public cl_setUp validKyc {
Can we try to stick to our test naming convention here 😁

2023-10-06 15:48 UTC, philbow61 commented on contracts/governance/Airgrab.sol
> +  uint32 public constant MAX_CLIFF_PERIOD = 103;
ok i see 👍

2023-10-06 17:01 UTC, baroooo commented on contracts/governance/Airgrab.sol
> +  uint32 public constant MAX_CLIFF_PERIOD = 103;
hmm I don't think so because it shifts everything back. my understanding is:
when you lock for a week between (N) and (N+1) the end date is (N+1). if you unlock 4 days later, you will receive full amount as 1 week is passed from contracts perspective, because 4 days later we are in a new epoch (N+1)

2023-10-06 17:07 UTC, baroooo approved these changes

2023-10-09 06:39 UTC, baroooo commented on .gitmodules
> +[submodule "lib/locking-contracts"]
I will update this once locking contracts are merged

2023-10-09 07:13 UTC, baroooo commented on test/governance/Airgrab.t.sol
> +  function test_Claim_canClaim_whenInvalidClaimAmount_reverts() public cl_setUp validKyc {
I think this is fine since it tests `canClaim` modifier on `claim` function

2023-10-09 08:15 UTC, merged