chore: fixed solhint warnings
mento-protocol/mento-core pull request #374
Opened 2024-02-16 13:50 UTC by chapati23

Fixed relevant and disabled irrelevant solhint warnings

2024-02-19 07:57 UTC, bowd requested changes
Looking good 🤩 just need to fix the `deployer -> DEPLOYER` situation to get CI green.

2024-02-19 07:57 UTC, bowd commented on test/utils/BaseTest.next.sol
> +  address public constant DEPLOYER = address(0x31337);
There are _a lot_  of references to this `deployer` in tests extending both this and the `0.5` version. I would say we maybe ignore the solhint warning here or make it a storage variable instead of a constant. Or if you're really feeling it, go deep and make all references uppercase :)

2024-02-19 10:05 UTC, bowd approved these changes

2024-02-20 13:37 UTC, nvtaveras requested changes

2024-02-20 13:37 UTC, nvtaveras commented on contracts/governance/TimelockController.sol
>  // solhint-disable-next-line max-line-length
no longer need this after the change?

2024-02-20 13:37 UTC, nvtaveras commented on contracts/governance/deployers/ProxyDeployerLib.sol
>  //solhint-disable-next-line max-line-length
ditto

2024-02-20 13:37 UTC, nvtaveras commented on contracts/tokens/patched/ERC20Upgradeable.sol
> +
delete?

2024-02-20 13:37 UTC, nvtaveras commented on test/fork-tests/TokenUpgrade.t.sol
> +  // solhint-disable-next-line func-name-mixedcase
is the mixedcase here because of the `_` ?

2024-02-20 15:23 UTC, chapati23 commented on contracts/governance/TimelockController.sol
>  // solhint-disable-next-line max-line-length
still needed unfortunately, if i remove it it complains

2024-02-20 15:25 UTC, chapati23 commented on contracts/tokens/patched/ERC20Upgradeable.sol
> +
this is re-enabling the rule after it was disabled for the previous block, it's a bit cleaner IMO because at least it's then linting the local var definitions instead of completely ignoring this rule

2024-02-20 15:25 UTC, chapati23 commented on test/fork-tests/TokenUpgrade.t.sol
> +  // solhint-disable-next-line func-name-mixedcase
yes

2024-02-21 00:58 UTC, nvtaveras approved these changes
Thanks for answering the comments!

2024-02-21 08:22 UTC, merged