Implement Chainlink relayer contract
mento-protocol/mento-core pull request #456
Opened 2024-06-14 14:58 UTC by m-chrzan

### Description

Adds a ChainlinkAdapter contract which can relay anwers from a Chainlink AggregatorV3 to SortedOracles.

It assumes it is the only reporter for the given rate feed in SortedOracles (e.g. `greater`/`lesserKey` are not needed).

Every rate feed that relies on this mechanism should have a separate ChainlinkAdapter deployed, with the appropriate parameters passed to the constructor. To save gas, the adapter is stateless, unupgradeable, and relies on immutable parameters set in the constructor.

Next steps:

* Integration test of the contract.
* Off-chain component that can ping this adapter contract.
* Deployment tooling/docs for setting up a rate feed with the ChainlinkAdapter.

### Tested

Unit tests.

2024-07-03 10:54 UTC, chapati23 requested changes

2024-07-03 10:54 UTC, chapati23 commented on contracts/interfaces/IChainlinkAdapter.sol
> +interface IChainlinkAdapter {
```suggestion
interface IChainlinkRelayer {
```

2024-07-03 10:54 UTC, chapati23 commented on contracts/interfaces/IChainlinkAdapter.sol
> +  function token() external returns (address);
```suggestion
  function rateFeedId() external returns (address);
```

2024-07-03 10:54 UTC, chapati23 commented on contracts/interfaces/IChainlinkAdapter.sol
> +  function aggregator() external returns (address);
```suggestion
  function chainlinkAggregator() external returns (address);
```

2024-07-03 10:54 UTC, chapati23 commented on contracts/oracles/ChainlinkAdapter.sol
> + * interface directly, so we use a minimal hand-copied one.
For convenience can we add a github link to SortedOracles interface here so it's easily verifiable that our hand-copying was accurate

2024-07-03 10:54 UTC, chapati23 commented on contracts/oracles/ChainlinkAdapter.sol
> + * @title ChainlinkAdapter
```suggestion
 * @title ChainlinkRelayer
```

2024-07-03 10:54 UTC, chapati23 commented on contracts/oracles/ChainlinkAdapter.sol
> + * @notice The ChainlinkAdapter relays rate feed data from a Chainlink oracle to
```suggestion
 * @notice The ChainlinkRelayer relays rate feed data from a Chainlink price feed to
```

2024-07-03 10:54 UTC, chapati23 commented on contracts/oracles/ChainlinkAdapter.sol
> + * @dev Assumes that it itself is the only reporter for the given SortedOracles
hmm, to what extent is this assumption relevant here?

2024-07-03 10:54 UTC, chapati23 commented on contracts/oracles/ChainlinkAdapter.sol
> +contract ChainlinkAdapter is IChainlinkAdapter {
```suggestion
contract ChainlinkRelayer is IChainlinkRelayer {
```

2024-07-03 10:54 UTC, chapati23 commented on contracts/oracles/ChainlinkAdapter.sol
> +  address public immutable token;
```suggestion
  address public immutable rateFeedId;
```

2024-07-03 10:54 UTC, chapati23 commented on contracts/oracles/ChainlinkAdapter.sol
> +  address public immutable aggregator;
```suggestion
  address public immutable chainlinkAggregator;
```

2024-07-03 10:54 UTC, chapati23 commented on contracts/oracles/ChainlinkAdapter.sol
> +  error OldTimestamp();
the more accurate name would be `NotANewTimestamp` or `NotNewerThan..` because `Old` suggests it is definitively older than SortedOracle's current one, when in reality there'll be many cases where the timestamps are identical between chainlink and sortedoracles, no?

struggling to find a succinct name that expresses this, some thoughts
- `TimestampNotNew()`
- `TimestampNotNewerThanSortedOracles()`

key point being that "old" is subtly different from "not new" in our case I think

2024-07-03 10:54 UTC, chapati23 commented on contracts/oracles/ChainlinkAdapter.sol
> +   * @notice Used when a new answer's timestamp is not newer than the most recent
```suggestion
   * @notice Used when a new price's timestamp is not newer than the most recent
```

I know chainlink calls this `answer` in their code, but feel like `price` is the more intuitive and concrete word here

2024-07-03 10:54 UTC, chapati23 commented on contracts/oracles/ChainlinkAdapter.sol
> +   * @notice Used when a new answer's timestamp would be considered expired by
```suggestion
   * @notice Used when a new price's timestamp would be considered expired by
```

2024-07-03 10:54 UTC, chapati23 commented on contracts/oracles/ChainlinkAdapter.sol
> +   * @notice Used when a negative answer is returned by the Chainlink
```suggestion
   * @notice Used when a negative price is returned by the Chainlink
```

2024-07-03 10:54 UTC, chapati23 commented on contracts/oracles/ChainlinkAdapter.sol
> +  error NegativeAnswer();
```suggestion
  error NegativePrice();
```

2024-07-03 10:54 UTC, chapati23 commented on contracts/oracles/ChainlinkAdapter.sol
> +   * @notice Initializes the contract, setting immutable parameters.
```suggestion
   * @notice Initializes the contract and sets immutable parameters.
```

2024-07-03 10:54 UTC, chapati23 commented on contracts/oracles/ChainlinkAdapter.sol
> +   * @param _token Address of the rate feed this adapter relays for.
```suggestion
   * @param _rateFeedId ID of the rate feed this relayer instance relays for.
```

2024-07-03 10:54 UTC, chapati23 commented on contracts/oracles/ChainlinkAdapter.sol
> +   * @param _aggregator Address of the Chainlink aggregator to fetch data from.
```suggestion
   * @param _chainlinkAggregator Address of the Chainlink price feed to fetch data from.
```

2024-07-03 10:54 UTC, chapati23 commented on contracts/oracles/ChainlinkAdapter.sol
> +    address _token,
```suggestion
    address _rateFeedId,
```

2024-07-03 10:54 UTC, chapati23 commented on contracts/oracles/ChainlinkAdapter.sol
> +    address _aggregator
```suggestion
    address _chainlinkAggregator
```

2024-07-03 10:54 UTC, chapati23 commented on contracts/oracles/ChainlinkAdapter.sol
> +    token = _token;
```suggestion
    rateFeedId = _rateFeedId;
```

2024-07-03 10:54 UTC, chapati23 commented on contracts/oracles/ChainlinkAdapter.sol
> +    aggregator = _aggregator;
```suggestion
    chainlinkAggregator = _chainlinkAggregator;
```

2024-07-03 10:54 UTC, chapati23 commented on contracts/oracles/ChainlinkAdapter.sol
> +   * @dev Checks the answer is non-negative (Chainlink uses `int256` rather
```suggestion
   * @dev Checks the price is non-negative (Chainlink uses `int256` rather
```

2024-07-03 10:54 UTC, chapati23 commented on contracts/oracles/ChainlinkAdapter.sol
> +   * @dev Converts the answer to a Fixidity value, as expected by
```suggestion
   * @dev Converts the price to a Fixidity value, as expected by
```

2024-07-03 10:54 UTC, chapati23 commented on contracts/oracles/ChainlinkAdapter.sol
> +    (, int256 answer, , uint256 timestamp, ) = AggregatorV3Interface(aggregator).latestRoundData();
```suggestion
    (, int256 answer, , uint256 timestamp, ) = AggregatorV3Interface(chainlinkAggregator).latestRoundData();
```

2024-07-03 10:54 UTC, chapati23 commented on contracts/oracles/ChainlinkAdapter.sol
> +    uint256 lastTimestamp = _sortedOracles.medianTimestamp(token);
```suggestion
    uint256 lastTimestamp = _sortedOracles.medianTimestamp(rateFeedId);
```

2024-07-03 10:54 UTC, chapati23 commented on contracts/oracles/ChainlinkAdapter.sol
> +      revert NegativeAnswer();
```suggestion
      revert NegativePrice();
```

2024-07-03 10:54 UTC, chapati23 commented on contracts/oracles/ChainlinkAdapter.sol
> +    ISortedOraclesMin(sortedOracles).report(token, report, address(0), address(0));
```suggestion
    ISortedOraclesMin(sortedOracles).report(rateFeedId, report, address(0), address(0));
```

2024-07-03 10:54 UTC, chapati23 commented on contracts/oracles/ChainlinkAdapter.sol
> +
a comment on why `address(0)` is fine here would be nice to have imo

2024-07-03 10:54 UTC, chapati23 commented on test/oracles/ChainlinkAdapter.t.sol
> +contract ChainlinkAdapterTest_relay is ChainlinkAdapterTest {
think we should also explicitly test the correct conversion of `int256 answer` to `uint256 priceInFixidityFormat`

maybe also some fuzz tests to ensure a variety of rates all get converted correctly

2024-07-03 13:15 UTC, m-chrzan commented on contracts/oracles/ChainlinkAdapter.sol
> + * @dev Assumes that it itself is the only reporter for the given SortedOracles
Just so future devs know this isn't a general Chainlink -> SortedOracles relayer that will work in every case, but instead needs to be in a setup where there aren't othe reporters for that rate feed (due to hardcoding lesser/greater keys to `address(0)`; technically, as discussed previously, this actually allows for up to *two* reporters for the feed, but no more).

2024-07-03 14:35 UTC, m-chrzan commented on test/oracles/ChainlinkAdapter.t.sol
> +contract ChainlinkAdapterTest_relay is ChainlinkAdapterTest {
Added [`testFuzz_convertsChainlinkToFixidityCorrectly`](https://github.com/mento-protocol/mento-core/pull/456/files#diff-e41049d6a1c786e606c257d3be3417c4f7e017e381f49232cfa326709f087353R66).

2024-07-04 10:50 UTC, chapati23 reviewed
looks great now, just one last question on version number

2024-07-04 10:50 UTC, chapati23 commented on contracts/oracles/ChainlinkRelayer.sol
> +contract ChainlinkRelayer is IChainlinkRelayer {
should we add the version here as well?

```suggestion
contract ChainlinkRelayerV1 is IChainlinkRelayer {
```

2024-07-09 10:08 UTC, baroooo requested changes

2024-07-09 16:00 UTC, m-chrzan commented on contracts/oracles/ChainlinkRelayerV1.sol
> +      if (isTimestampExpired(timestamp)) {
Good catch. I don't think it would reject subsequent fresh rates, but yeah, could accept a stale rate in the edge case of the first report.

Fixed and added a regression test.

2024-07-10 07:58 UTC, baroooo commented on contracts/oracles/ChainlinkRelayerV1.sol
> +      if (isTimestampExpired(timestamp)) {
yeah, I meant the subsequent "stale" rates would be rejected.
fix looks good!

2024-07-10 07:58 UTC, baroooo approved these changes

2024-07-15 10:33 UTC, merged