Feat/good dollar work
mento-protocol/mento-core pull request #468
Opened 2024-06-20 21:07 UTC by philbow61

### Description

_A few sentences describing the overall effects and goals of the pull request's commits.
What is the current behavior, and what is the updated/expected behavior with this PR?_

### Other changes

_Describe any minor or "drive-by" changes here._

### Tested

_An explanation of how the changes were tested or an explanation as to why they don't need to be._

### Related issues

- Fixes #[issue number here]

### Backwards compatibility

_Brief explanation of why these changes are/are not backwards compatible._

### Documentation

_The set of community facing docs that have been added/modified because of this change_

2024-06-23 05:45 UTC, sirpy commented on contracts/goodDollar/GoodDollarExpansionController.sol
> +      emit UBIMinted(exchangeId, amountMinted);
add a variable that differentiate between the different ubi minting.
also add a variable for the interest/additional reserve balance used

2024-06-23 05:46 UTC, sirpy commented on contracts/goodDollar/GoodDollarExpansionController.sol
> +      IGoodDollar(exchange.tokenAddress).mint(address(distributionHelper), amountMinted);
i've sent you the code how to mint.
minting needs to go through the dao controller

2024-07-02 12:30 UTC, sirpy requested changes
partial review more comming tomorrow
@bowd @philbow61

2024-07-02 12:30 UTC, sirpy commented on contracts/goodDollar/GoodDollarExchangeProvider.sol
> +contract GoodDollarExchangeProvider is IGoodDollarExchangeProvider, BancorExchangeProvider, PausableUpgradeable {
I dont see upgrade access control in any of the contracts

2024-07-02 12:30 UTC, sirpy commented on contracts/goodDollar/BancorExchangeProvider.sol
> +  mapping(address => uint256) public tokenPrecisionMultipliers;
probably should add reserved space for upgrades

2024-07-02 12:30 UTC, sirpy commented on contracts/goodDollar/GoodDollarExchangeProvider.sol
> +  address public AVATAR;
reserve space for upgrades?

2024-07-02 12:30 UTC, sirpy commented on contracts/goodDollar/GoodDollarExchangeProvider.sol
> +  function setExpansionController(address _expansionController) public onlyOwner {
should be onlyAvatar

2024-07-02 12:30 UTC, sirpy commented on contracts/goodDollar/GoodDollarExpansionController.sol
> +      uint256 stepExpansionScaler = MAX_WEIGHT - config.expansionRate;
why? this actually requires to set expansion rate to the inverse of the rate.
should add docs in function comments where relevant

2024-07-02 12:30 UTC, sirpy commented on contracts/goodDollar/GoodDollarExchangeProvider.sol
> +    PoolExchange memory exchange = getPoolExchange(exchangeId);
what will happen if exchange doesnt exists?

2024-07-03 08:18 UTC, sirpy requested changes
Missing some upgrade tests

2024-07-03 08:18 UTC, sirpy commented on contracts/goodDollar/GoodDollarExpansionController.sol
> +  function setDistributionHelper(address _distributionHelper) public onlyOwner {
should be only avatar

2024-07-03 08:18 UTC, sirpy commented on contracts/goodDollar/GoodDollarExpansionController.sol
> +  function setAvatar(address _avatar) public onlyOwner {
should be onlyavatar

2024-07-03 08:18 UTC, sirpy commented on contracts/goodDollar/GoodDollarExpansionController.sol
> +   * @param expansionFrequency The frequency of expansion.
need better docs explaining the units

2024-07-03 08:18 UTC, sirpy commented on contracts/goodDollar/GoodDollarExpansionController.sol
> +    if (shouldExpand || config.lastExpansion == 0) {
i would simply initialize lastExpansion to current timestamp in initialize

2024-07-03 08:18 UTC, sirpy commented on contracts/goodDollar/GoodDollarExpansionController.sol
> +      if (config.lastExpansion == 0) {
see above comment

2024-07-03 08:18 UTC, sirpy commented on contracts/goodDollar/BancorExchangeProvider.sol
> +      scaledAmountIn = (scaledAmountIn * (MAX_WEIGHT - exchange.exitConribution)) / MAX_WEIGHT;
why the inverse of exitContribution?

2024-07-05 11:52 UTC, philbow61 commented on contracts/goodDollar/GoodDollarExpansionController.sol
> +      uint256 stepExpansionScaler = MAX_WEIGHT - config.expansionRate;
Not sure what you mean by inverse.
The expansion rate currently is a percentage with 100%<= expansionRtae <= 0.
e.g expansionRate of 1% means we need to multiply the reserveRatio by the scaler 0.99 per expansion

2024-07-05 11:52 UTC, philbow61 commented on contracts/goodDollar/GoodDollarExchangeProvider.sol
> +    PoolExchange memory exchange = getPoolExchange(exchangeId);
It will revert.

2024-07-05 11:54 UTC, philbow61 commented on contracts/goodDollar/GoodDollarExpansionController.sol
> +    if (shouldExpand || config.lastExpansion == 0) {
Initially, I had it this way Bogdan preferred the one expansion after configuration let's have a chat about this in the next sync

2024-07-05 11:56 UTC, philbow61 commented on contracts/goodDollar/BancorExchangeProvider.sol
> +      scaledAmountIn = (scaledAmountIn * (MAX_WEIGHT - exchange.exitConribution)) / MAX_WEIGHT;
because we are calculating the amountIn the math comes from the notion doc for reference 
https://www.notion.so/mentolabs/G-Reserve-Design-ba81a27b6268422a875bedbcd94ba2db?pvs=4#0319ceadad8b4edaaca898e9545e1057

2024-07-05 11:57 UTC, philbow61 commented on contracts/goodDollar/GoodDollarExpansionController.sol
> +  function setAvatar(address _avatar) public onlyOwner {
lets have another chat together about access control on the different functions

2024-07-05 11:59 UTC, philbow61 commented on contracts/goodDollar/BancorExchangeProvider.sol
> +  function _getAmountIn(
not sure what you mean it's applied in L362

2024-07-05 12:00 UTC, philbow61 commented on contracts/goodDollar/BancorFormula.sol
> +contract BancorFormula {
everything described in the comment above

2024-07-05 12:03 UTC, philbow61 commented on contracts/goodDollar/GoodDollarExchangeProvider.sol
> +    setAvatar(_avatar);
msg.sender calls initialize -> ownership is transferred to msg.sender -> setters are called which are onlyOwner
I don't see the problem tests verified this behavior

2024-07-07 09:08 UTC, sirpy commented on contracts/goodDollar/GoodDollarExpansionController.sol
> +      uint256 stepExpansionScaler = MAX_WEIGHT - config.expansionRate;
ok

2024-07-07 09:08 UTC, sirpy commented on contracts/goodDollar/GoodDollarExchangeProvider.sol
> +    setAvatar(_avatar);
ok

2024-07-07 09:09 UTC, sirpy commented on contracts/goodDollar/BancorExchangeProvider.sol
> +      scaledAmountIn = (scaledAmountIn * (MAX_WEIGHT - exchange.exitConribution)) / MAX_WEIGHT;
ok

2024-08-11 09:08 UTC, sirpy commented on contracts/goodDollar/interfaces/IBancorExchangeProvider.sol
> +  function currentPrice(bytes32 exchangeId) external returns (uint256 price);
should be view

2024-08-14 11:09 UTC, sirpy commented on contracts/goodDollar/BancorExchangeProvider.sol
> +    exchange.exitConribution = exitContribution;
typo `exitContribution`

2024-10-14 10:33 UTC, closed without merging