feat: add Broker liquidity check
mento-protocol/mento-core pull request #523
Opened 2024-10-09 10:17 UTC by philbow61

### Description

This Pr adds a check on Broker quotes ensuring that if the TokenOut is a collateral asset the reserve can match the amountOut if not the call reverts. 

### Other changes

### Tested

fixed the test + added additional unit tests 

### Related issues

- Fixes https://github.com/mento-protocol/mento-general/issues/554

### Backwards compatibility

### Documentation

2024-10-10 00:34 UTC, bayological requested changes

2024-10-10 00:34 UTC, bayological commented on contracts/swap/Broker.sol
> +    if (IReserve(reserve).isCollateralAsset(tokenOut)) {
Would be more efficient to extract this check and move it before `exchangeProvider.getAmountOut` ?

2024-10-10 00:34 UTC, bayological commented on contracts/swap/Broker.sol
> +      require(IERC20(tokenOut).balanceOf(reserve) >= amountOut, "Insufficient balance in reserve");
This check could be bypassed by sending enough `tokenOut` to the reserve. Could this be problematic down the line?

2024-10-10 12:59 UTC, chapati23 commented on contracts/swap/Broker.sol
> +    if (IReserve(reserve).isCollateralAsset(tokenOut)) {
we need `amountOut` in the require condition, so I think in this case the check can't happen before

wrt extracting I'm indifferent, would be slightly cleaner to DRY this up by creating a little `ensureReserveHasAtLeast(uint256 amount, address token)` helper but would also slightly increase gas cost

2024-10-10 14:16 UTC, bayological commented on contracts/swap/Broker.sol
> +    if (IReserve(reserve).isCollateralAsset(tokenOut)) {
Specifically the isCollateralAsset(tokenOut) check but tbh the gains would be minimal.

2024-10-10 15:05 UTC, chapati23 approved these changes
nice work, just some stylistic comments/suggestions for the tests

2024-10-10 15:05 UTC, chapati23 commented on test/unit/swap/Broker.t.sol
> +  function test_getAmountIn_whenReserveBalanceIsLessThanAmountOut_shouldRevert() public {
Even though it's functionally redundant, it could make the code a tad nicer to read if you explicitly minted 0 just to show that the reserve doesn't have enough:

```sol
collateralAsset.mint(address(reserve), 0);
```

2024-10-10 21:49 UTC, bayological approved these changes

2024-10-16 09:25 UTC, baroooo approved these changes

2024-10-16 10:02 UTC, merged