Feat(454): Exchange provider tests
mento-protocol/mento-core pull request #529
Opened 2024-10-16 14:15 UTC by RyRy79261

### Description

This PR adds additional tests to to the exchange provider and includes fuzz testing

### Related issues

- Fixes https://github.com/mento-protocol/mento-general/issues/454
-

2024-10-21 09:28 UTC, bowd commented on test/unit/goodDollar/GoodDollarExchangeProvider.t.sol
> +    // vm.assume(expansionScaler > 3 && expansionScaler < 1e18);
Delete line

2024-10-21 09:48 UTC, bowd requested changes

2024-10-21 09:48 UTC, bowd commented on test/unit/goodDollar/GoodDollarExchangeProvider.t.sol
> +  function testFuzz_mintFromExpansion(uint256 expansionScaler) public {
This is I guess a conceptual nit pick I have with this test. I dislike the idea of reimplementing logic in test and validating against it. What we're kinda saying here is that we have this logic that calculates the expected mint, and also this logic that determines the new ratio, and it's somewhere in a contract and we're reimplementing it in the test and validating that we've done that correctly. And then we're also doing it in a fuzz test.

TBH I'd do something a bit more easy and general here. Given that we're fuzzing for the expansion scalar, I would assert that, if expansion scalar <100% (i.e. we're making the reserve ration smaller, i.e. we're going to mint more stables) then amountToMint > 0, and I think we can also estimate the amountToMint as a delta around currentSupply * (1/expansionScaler - 1) (off the dome so this might be wrong). And I would also only assert that the newRatio < oldRatio.

2024-10-21 09:48 UTC, bowd commented on test/unit/goodDollar/GoodDollarExchangeProvider.t.sol
> +    // vm.assume(expansionScaler > 3 && expansionScaler < 1e18);
Delete line

2024-10-21 09:48 UTC, bowd commented on test/unit/goodDollar/GoodDollarExchangeProvider.t.sol
> +  function testMintFromExpansion_RevertWhenNewRatioIsZero() public {
Missing a new line

2024-10-21 09:48 UTC, bowd commented on test/unit/goodDollar/GoodDollarExchangeProvider.t.sol
> +    // Add more assertions to check the final state
Should we?

2024-10-21 09:48 UTC, bowd commented on test/unit/goodDollar/GoodDollarExchangeProvider.t.sol
> +  }
Just bellow 100% is minimum expansion. maximum expansion is the smallest possible expansionScalar. Outside of this PR but I don't really like the naming here. 
I think `expansionScaler` should be `reserveRatioScaler` or `reserveRatioScaleFactor`.

2024-10-21 09:55 UTC, RyRy79261 commented on test/unit/goodDollar/GoodDollarExchangeProvider.t.sol
> +  function testFuzz_mintFromExpansion(uint256 expansionScaler) public {
I did mention this in the discussions, but because we haven't got any external contracts which rely on the output value to be accurate, or lining up with expectations externally. 

Is your recommendation to: 

```
if expansion < 100% && amountToMint > 0 {
   assertApproximateEq: amountToMint, (currentSupply * (1/expansionScalar - 1));
}
```

2024-10-21 11:22 UTC, philbow61 commented on test/unit/goodDollar/GoodDollarExchangeProvider.t.sol
> +
Can we maybe add an assertEq here with an expectedAmountToMint that you calculate off-chain and verify against?

2024-10-21 11:32 UTC, RyRy79261 commented on test/unit/goodDollar/GoodDollarExchangeProvider.t.sol
> +  }
@bowd This is a bit confusing, maximum is the smallest possible scalar, with minimum being 100% - 1/

That reads as the max and min are the same value. What would the maximum be then?

2024-10-21 11:34 UTC, philbow61 requested changes
LGTM, left some little nits/suggestions.
Can we change the fuzz tests such that the PoolConfig they are running on is the Config the system will most likely be deployed with. The config is in our G$ discord group chat.

2024-10-21 11:35 UTC, RyRy79261 commented on test/unit/goodDollar/GoodDollarExchangeProvider.t.sol
> +    // Add more assertions to check the final state
This was based off not having a way to confirm total minted in a way that isn't redundant

2024-10-21 11:35 UTC, RyRy79261 commented on test/unit/goodDollar/GoodDollarExchangeProvider.t.sol
> +
@philbow61 for the calculation offchain, do you mean dynamically within the test, or hardcoded in the test?

2024-10-21 11:37 UTC, philbow61 commented on test/unit/goodDollar/GoodDollarExchangeProvider.t.sol
> +
just hardcoded in the test 😁

2024-10-21 13:54 UTC, RyRy79261 commented on test/unit/goodDollar/GoodDollarExchangeProvider.t.sol
> +
@philbow61 What values would make the most sense for checkings this?

2024-10-21 15:17 UTC, RyRy79261 commented on test/unit/goodDollar/GoodDollarExchangeProvider.t.sol
> +
Wolfram Alpha isn't providing answers that are easily hardcoded into this: 
https://www.wolframalpha.com/input?i=%28115792089237316195423570985008687907853269984665640564039457584007913129639935+%2F+%287000000000+**+18%29%29++%2F+%28200000+**18%29

The token amount on max interest with expected config, is this fraction:
```23158417847463239084714197001737581570653996933128112807891516801582625927987/85375770842127348531200000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
```

2024-10-23 10:10 UTC, baroooo approved these changes

2024-10-23 10:10 UTC, baroooo commented on test/unit/goodDollar/GoodDollarExchangeProvider.t.sol
> +    assertLe(poolExchangeAfter.reserveRatio, initialReserveRatio, "Reserve ratio should decrease");
```suggestion
    assertLe(poolExchangeAfter.reserveRatio, initialReserveRatio, "Reserve ratio should stay the same or decrease");
```

2024-10-23 14:22 UTC, nvtaveras approved these changes

2024-10-23 14:28 UTC, merged