feat: add cCOP fork tests
mento-protocol/mento-core pull request #537
Opened 2024-10-30 10:22 UTC by nvtaveras

### Description

Add fork tests for $cCOP

2024-11-04 16:50 UTC, philbow61 requested changes
LGTM.
I added the cCOP exhchage on mainnet but alfajores tests are failing because of 2 reasons:
1. oracle problems 
2. It looks like cCOP proposal wasn't executed on alfajores I assume the reason is that mu0Next was already executed on alfajores and the cCOP upgrade is causing problems with FixidityLib in 0.8

Therefore I would suggest we wait until cCOP is executed on testnets before merging this one

2024-11-05 11:07 UTC, chapati23 requested changes
I rebased on top of the latest develop and had to fix some resulting compilation errors to get this to run.

Both alfajores and mainnet fork tests are failing for me rn, alfajores because of what @philbow61 said and 3 rate feeds being down rn

2024-11-05 11:31 UTC, chapati23 approved these changes
we fixed the mainnet fork tests now, alfajores is broken right now because of broken rate feeds but we're fine with merging regardless

2024-11-05 15:46 UTC, philbow61 approved these changes

2024-11-05 15:50 UTC, merged