Feature/make broker capable of minting
mento-protocol/mento-core pull request #68
Opened 2022-11-15 14:09 UTC by philbow61

### Description

- added the `BROKER_REGISTRY_ID` to the StableToken contract 
- both `mint()` and `burn()` now also check whether the caller is the broker address from the registry
- thereby allowing a registered broker to mint and burn 

### Tested

- updated the McMintIntegration.sol
- The migrated StableToken.t.sol is currently on develop. Therefore I would suggest writing the same test for [mint](https://github.com/mento-protocol/mento-core/blob/dedb150aed90d44a4239d5a6e558fe6836da276c/test/StableToken.t.sol#L183) and [burn](https://github.com/mento-protocol/mento-core/blob/dedb150aed90d44a4239d5a6e558fe6836da276c/test/StableToken.t.sol#L471) when develop and McMint are merged. 

### Related issues

- Fixes #32

2022-11-16 15:35 UTC, ninocomputer requested changes
looks good, but I wish there were unit tests to verify that changes in the contract work as expected.

2022-11-16 15:35 UTC, ninocomputer commented on test/utils/McMintIntegration.sol
> +  address exchange;
why are you using exchange instead of broker?

2022-11-16 15:50 UTC, philbow61 commented on test/utils/McMintIntegration.sol
> +  address exchange;
Before my branch the `exchangeIdentifier` of the stableToken was set to "Broker" this workaround allowed the broker to mint. Since the Broker is now capable of minting by itself I removed the "Broker" and replaced it with "Exchange"

2022-11-16 15:55 UTC, philbow61 commented
> looks good, but I wish there were unit tests to verify that changes in the contract work as expected.

@ninocomputer I tried to address the unit test in the description of this PR. The stableToken.t.sol is not yet on this branch that's why I would suggest we add them to the existing mint and burn stable token tests as soon as the branches are merged. But maybe there is a better way of doing this?

2022-11-16 16:07 UTC, ninocomputer commented
> > looks good, but I wish there were unit tests to verify that changes in the contract work as expected.
> 
> @ninocomputer I tried to address the unit test in the description of this PR. The stableToken.t.sol is not yet on this branch that's why I would suggest we add them to the existing mint and burn stable token tests as soon as the branches are merged. But maybe there is a better way of doing this?

@philbow61 you can try cherry pick StableToken test commit on your branch

2022-11-17 18:04 UTC, ninocomputer approved these changes
looks good! 👍🏼

2022-11-17 18:09 UTC, merged