feat: On-chain Circuit Breaker
mento-protocol/mento-core pull request #71
Opened 2022-11-17 17:21 UTC by bowd

### Description

- [x] moving initial circuit breaker implementation from [celo-monorepo](https://github.com/celo-org/celo-monorepo/pull/9677) to mento core. 
- [x] Add reference to the BreakerBox in the BiPoolManager
- [x] Query the breaker box by using the oracleReportTarget variable in the pair details
- [x] Write tests to verify everything works as expected

_circuit breaker integration with McMint design doc can be found [here](https://www.notion.so/e62010a140154271a48aba711a9f897a?v=35252ec445274fcf93043604e39f6733&p=3ffd6d250a074efb8b952714c90ec64f&pm=s)_

### Other changes

N/A

### Tested

- Unit tests
- Integration tests

### Related issues

- Fixes #35

2022-11-18 21:00 UTC, bayological requested changes

2022-11-18 21:00 UTC, bayological commented on contracts/BiPoolManager.sol
> +    if (address(breakerBox) != address(0)) {
The first line in the setBreakerBox function checks if the given address is 0. Why is this check necessary?

2022-11-18 21:00 UTC, bayological commented on contracts/interfaces/IBreakerBox.sol
> +   * @param rateFeedID The address of the rataFeedID.
Typo.

```suggestion
   * @param rateFeedID The address of the rateFeedID.
```

2022-11-18 21:00 UTC, bayological commented on contracts/proxies/BreakerProxy.sol
> +contract BreakerBoxProxy is Proxy {
This file is named incorrectly.

2022-11-18 23:10 UTC, bayological requested changes

2022-11-18 23:11 UTC, bayological requested changes

2022-11-18 23:11 UTC, bayological commented on contracts/BreakerBox.sol
> +    require(sortedOracles.getOracles(rateFeedID).length > 0, "Rate feed ID does not exist in oracles list");
This message could be re-worded for clarity. The rateFeedID will never be in the oracles list because it's not an oracle. In this context, it's valid to say the rate feed does not exist as it has 0 oracles.

2022-11-18 23:23 UTC, bayological commented on contracts/interfaces/IBreaker.sol
> +  function shouldTrigger(address exchange) external view returns (bool triggerBreaker);
To avoid confusion this param should be renamed so it's inline with the McMint changes.

2022-11-18 23:29 UTC, bayological requested changes

2022-11-18 23:29 UTC, bayological commented on contracts/interfaces/IBreaker.sol
> +  function shouldReset(address exchange) external view returns (bool resetBreaker);
To avoid confusion this function param should be renamed so it's inline with the McMint changes.

2022-11-18 23:29 UTC, bayological commented on contracts/MedianDeltaBreaker.sol
> +  function shouldTrigger(address exchange) public view returns (bool triggerBreaker) {
To avoid confusion, this param should be renamed along with the comment so it's inline with the McMint changes.

2022-11-18 23:29 UTC, bayological commented on contracts/MedianDeltaBreaker.sol
> +    uint256 previousMedian = sortedOracles.previousMedianRate(stableToken);
The argument being passed here is incorrect now. This should be the reference rate feed id.

2022-11-18 23:29 UTC, bayological commented on contracts/MedianDeltaBreaker.sol
> +    address stableToken = IExchange(exchange).stable();
This call is no longer needed.

2022-11-18 23:29 UTC, bayological commented on contracts/MedianDeltaBreaker.sol
> +    (uint256 currentMedian, ) = sortedOracles.medianRate(stableToken);
This arg is incorrect. As with the call above this should bow be the reference rate feed id

2022-11-21 14:12 UTC, ninocomputer commented on contracts/BiPoolManager.sol
> +    if (address(breakerBox) != address(0)) {
looks like this is a dangling check after I migrated from Registry to setting it in initialize.

2022-11-21 14:22 UTC, ninocomputer commented on contracts/BiPoolManager.sol
> +  function checkTradingMode(PoolExchange memory exchange) public view {
good suggestion 👍🏼

2022-11-21 14:27 UTC, ninocomputer commented on test/utils/McMintIntegration.sol
> +  address cUSD_CELO_rateFeedID;
It has to be **referenceRateFeedID**

2022-11-21 14:53 UTC, ninocomputer commented on contracts/BreakerBox.sol
> +    require(sortedOracles.getOracles(rateFeedID).length > 0, "Rate feed ID does not exist in oracles list");
gotcha!

2022-11-21 15:08 UTC, ninocomputer commented on contracts/interfaces/IBreaker.sol
> +  function shouldTrigger(address exchange) external view returns (bool triggerBreaker);
👍🏼

2022-11-21 15:08 UTC, ninocomputer commented on contracts/interfaces/IBreaker.sol
> +  function shouldReset(address exchange) external view returns (bool resetBreaker);
👍🏼

2022-11-21 19:15 UTC, bayological requested changes

2022-11-21 19:15 UTC, bayological commented on test/MedianDeltaBreaker.t.sol
> +  MockExchange testExchange;
References to any exchange-related code are not needed and should be removed.

2022-11-21 19:15 UTC, bayological commented on test/MedianDeltaBreaker.t.sol
> +    vm.mockCall(address(testExchange), abi.encodeWithSelector(testExchange.stable.selector), abi.encode(testStable));
Not needed,

2022-11-21 19:15 UTC, bayological commented on test/SortedOracles.t.sol
> +  function test_report_shouldCallBreakerBoxWithExchangeId() public {
This test name is now misleading. IT mentions the exchange ID but this is now no longer present. Please rename it to something that accurately describes the intention.

2022-11-21 19:15 UTC, bayological commented on test/SortedOracles.t.sol
> +    vm.expectCall(address(mockBreakerBox), abi.encodeWithSelector(mockBreakerBox.checkAndSetBreakers.selector));
We should be checking the function call also receives the correct argument (refRateId)

2022-11-21 19:15 UTC, bayological commented on test/utils/McMintIntegration.sol
> +import { MockBreakerBox } from "../mocks/MockBreakerBox.sol";
We should not be using mocks in integration tests. This kind of defeats the purpose of this test. Sorted oracles will be the only exception for now, as it depends on the external oracle clients. But for the circuit breaker, we should be using the actual implementations and setting them up as they should be when deployed. Please add the breaker box and breakers, initialise them and set them up properly.

2022-11-21 19:35 UTC, ninocomputer commented on test/MedianDeltaBreaker.t.sol
> +  MockExchange testExchange;
👍🏼

2022-11-21 19:35 UTC, ninocomputer commented on contracts/MedianDeltaBreaker.sol
> +import { IExchange } from "./interfaces/IExchange.sol";
👍🏼

2022-11-21 19:36 UTC, ninocomputer commented on contracts/MedianDeltaBreaker.sol
> +    (uint256 currentMedian, ) = sortedOracles.medianRate(stableToken);
👍🏼

2022-11-21 19:36 UTC, ninocomputer commented on contracts/MedianDeltaBreaker.sol
> +    address stableToken = IExchange(exchange).stable();
👍🏼

2022-11-21 19:36 UTC, ninocomputer commented on contracts/MedianDeltaBreaker.sol
> +    uint256 previousMedian = sortedOracles.previousMedianRate(stableToken);
👍🏼

2022-11-21 19:36 UTC, ninocomputer commented on contracts/MedianDeltaBreaker.sol
> +  function shouldTrigger(address exchange) public view returns (bool triggerBreaker) {
👍🏼

2022-11-21 19:37 UTC, ninocomputer commented on test/MedianDeltaBreaker.t.sol
> +    vm.mockCall(address(testExchange), abi.encodeWithSelector(testExchange.stable.selector), abi.encode(testStable));
👍🏼

2022-11-21 20:58 UTC, ninocomputer commented on test/SortedOracles.t.sol
> +  function test_report_shouldCallBreakerBoxWithExchangeId() public {
👍🏼

2022-11-21 21:50 UTC, ninocomputer commented on test/SortedOracles.t.sol
> +    vm.expectCall(address(mockBreakerBox), abi.encodeWithSelector(mockBreakerBox.checkAndSetBreakers.selector));
👍🏼

2022-11-21 22:24 UTC, ninocomputer commented on contracts/BiPoolManager.sol
> +  function checkTradingMode(PoolExchange memory exchange) public view {
I changed the logic a tiny bit. Moved this require statement in swapIn() and swapOut() functions, where checkTradingMode() was called in the first place. I think this implementation is more straight-forward and clean.

2022-11-23 02:27 UTC, bayological commented on test/utils/McMintIntegration.sol
> +    medianDeltaBreaker = new MedianDeltaBreaker(coolDownTime, threshold, ISortedOracles(address(sortedOracles)));
The circuit breaker setup is not complete. You need to add the MedianDeltaBreaker to the breaker box in order for it to be checked when swaps are executed.

2022-11-23 06:37 UTC, bowd commented on test/utils/McMintIntegration.sol
> +    medianDeltaBreaker = new MedianDeltaBreaker(coolDownTime, threshold, ISortedOracles(address(sortedOracles)));
Actually, it's a bit more complicated than that because we're using `MockSortedOracles` here so the Circuit Breaker isn't actually tested correctly unless we use the proper `SortedOracles`. This would require more test setup, but it would ultimately be helpful and improve the integration-ness of tests.

I'm going to give it a shot @ninocomputer and if I hit walls I'll probably choose to handle this in a different PR, to get this one merged.

2022-11-23 08:33 UTC, ninocomputer commented on test/utils/McMintIntegration.sol
> +    medianDeltaBreaker = new MedianDeltaBreaker(coolDownTime, threshold, ISortedOracles(address(sortedOracles)));
thank you @bayological for the review. Yes, it would be great if we could have a proper SortedOracles setup for integration testing. lmk if I can help @bowd

2022-11-23 12:09 UTC, bowd commented
@bayological / @ninocomputer done making the integration tests use SortedOracles + added a test for the circuit breaker.

2022-11-23 17:19 UTC, bayological approved these changes
LGTM

2022-11-23 17:20 UTC, merged