Feature/create npm package
mento-protocol/mento-core pull request #78
Opened 2022-11-28 17:31 UTC by philbow61

### Description

- created a npm mento organization @mentolabs
- created a npm package that contains typescript types and factories
- created a workflow that automatically generates the types/factories (generateTypes.js), builds them and publishes them 
- the workflow is triggered by a commit to the feature/mcmint branch in which the contracts/interfaces folder has changed

### Other changes

- in order for the build step to run I had to add @node/node: 18.11.9 to our mento-core devDependencies 
- before an older version of the same package was required by a different dependency 
- this older version caused errors with the typescript package needed for the build step 

### Tested

- in order to test the package I installed the package and interacted with the deployed mcmint contracts on baklava 
- https://github.com/dethcrypto/TypeChain/tree/master/packages/target-ethers-v5

### Related issues

- Fixes #12

2022-11-29 11:52 UTC, tobikuhlmann requested changes
Neat PR, Philip! It looks good to me. 

The only thing that I think is missing, already from the issue description, is a license for mento-core and the npm package. It would probably be specified in `package.json` and `package/package.json` like in celo-monorepo: https://github.com/celo-org/celo-monorepo/blob/master/package.json#L5. 

Can you add an Apache 2.0 license if there are no objections to it on Discord? (let's give people time to object until the engineering sync later)

2022-11-29 12:08 UTC, bowd requested changes
Hey @philbow61 I know I actually sent you down this path but now that I look at it again I think we made a wrong turn.
I'd like to actually only have one `package.json` at the top of the repo and not use this subfolder approach for building the npm package.

I think we initially did this because we had a failing `postinstall` related to `husky`.
Check the [docs](https://typicode.github.io/husky/#/?id=yarn-2) here on how to deal with that using the `pinst` helper.

Then I'd like the structure to actually be:
```
contracts/ -> the contracts
src/ -> where the typescript types and factories get generated
dist/ -> where the javascript is compiled from the typescript in `src`
```

Also I'd add an `.npmignore` file with at least:
```
.env
test
lib
```

2022-12-02 09:28 UTC, tobikuhlmann approved these changes
yup

2022-12-02 11:07 UTC, philbow61 commented
@tobikuhlmann instead of blacklisting files via the .npmignore we are using the files array within the package.json to explicitly  whitelist files for the package.

2022-12-02 12:49 UTC, MentoProtocolAdmin commented
👌

2022-12-02 12:51 UTC, tobikuhlmann commented
👌

2022-12-02 15:40 UTC, bowd requested changes

2022-12-02 15:40 UTC, bowd commented on generateTypes.js
> +}
Code formatting here is a bit weird - first indent is two spaces, 2nd indent is 1 space, the brackets at the end of the block are at the same level. can you clean it up pls!

2022-12-02 16:13 UTC, merged