Value delta breaker
mento-protocol/mento-core pull request #86
Opened 2022-12-07 11:31 UTC by bowd

### Description

Value Delta Breaker is an extension of the Median Delta Breaker, but instead of moving with the median, this breaker ensures that the oracle value always stays in a threshold of a reference value. This is useful for the USDC/USD oracles where we want to ensure that trading stops if the reported USDC price moves outside of a comfortable range, 1 USD +/- 5bps for example.

### Other changes

Because breakers share a lot of logic when it comes to their cooldown and threshold management, I abstracted that away in utility contracts that are shared by both the MedianDeltaBreaker and the ValueDeltaBreaker.

### Tested

Copied over the MedianDeltaBreaker tests and changed them accordingly.

### Related issues

- Fixes #85 

### Backwards compatibility

Changes are additive

### Documentation

The BreakerBox doc need to be updated.

2022-12-09 01:40 UTC, bayological commented on test/ValueDeltaBreaker.t.sol
> +  function test_setCooldownTime_whenCallerIsNotOwner_shouldRevert() public {
Test naming.
```suggestion
  function test_setDefaultCooldownTime_whenCallerIsNotOwner_shouldRevert() public {
```

2022-12-09 01:40 UTC, bayological commented on test/ValueDeltaBreaker.t.sol
> +  function test_setRateChangeThreshold_whenValueGreaterThanOne_shouldRevert() public {
Test naming.
```suggestion
  function test_setDefaultRateChangeThreshold_whenValueGreaterThanOne_shouldRevert() public {
```

2022-12-09 01:40 UTC, bayological commented on test/ValueDeltaBreaker.t.sol
> +  function test_setRateChangeThreshold_whenCallerIsOwner_shouldUpdateAndEmit() public {
Test naming.
```suggestion
  function test_setDefaultRateChangeThreshold_whenCallerIsOwner_shouldUpdateAndEmit() public {
```

2022-12-09 01:40 UTC, bayological commented on contracts/ValueDeltaBreaker.sol
> +  function setCooldownTimes(address[] calldata rateFeedIDs, uint256[] calldata cooldownTimes) external onlyOwner {
We should add a test that verifies this function works as expected. Maybe consider adding tests for the logic of both WithCoolDown & WithThreshold to separate tests then in the individual breaker tests we can just verify access control works as intended?

2022-12-09 01:40 UTC, bayological commented on test/ValueDeltaBreaker.t.sol
> +  function test_setRateChangeThreshold_whenSenderIsNotOwner_shouldRevert() public {
Typo.
```suggestion
  function test_setRateChangeThresholds_whenSenderIsNotOwner_shouldRevert() public {
```

2022-12-09 01:40 UTC, bayological commented on test/ValueDeltaBreaker.t.sol
> +  function test_setRateChangeThreshold_whenValuesAreDifferentLengths_shouldRevert() public {
Typo.
```suggestion
  function test_setRateChangeThresholds_whenValuesAreDifferentLengths_shouldRevert() public {
```

2022-12-09 01:40 UTC, bayological commented on test/ValueDeltaBreaker.t.sol
> +  function test_setRateChangeThreshold_whenThresholdIsMoreThan0_shouldRevert() public {
Typo.
```suggestion
  function test_setRateChangeThresholds_whenThresholdIsMoreThan0_shouldRevert() public {
```

2022-12-09 01:40 UTC, bayological commented on test/ValueDeltaBreaker.t.sol
> +  function test_setRateChangeThreshold_whenSenderIsOwner_shouldUpdateAndEmit() public {
```suggestion
  function test_setRateChangeThresholds_whenSenderIsOwner_shouldUpdateAndEmit() public {
```

2022-12-09 01:40 UTC, bayological commented on contracts/MedianDeltaBreaker.sol
> +// SPDX-Liaense-Identifier: UNLICENSED
```suggestion
// SPDX-License-Identifier: UNLICENSED
```

2022-12-09 01:40 UTC, bayological commented on contracts/MedianDeltaBreaker.sol
> +    // setRateChangeThresholds(rateFeedIDs, rateChangeThresholds);
Assuming this is intentional, we should remove the comment. But also, why not initialise the thresholds on deployment?

2022-12-09 01:40 UTC, bayological commented on test/MedianDeltaBreaker.t.sol
> +    stdstore.target(address(breaker)).sig(0x7dffc308).with_key(_rateFeedID).checked_write(previousMedianRate);
Nice.🧙‍♂️

2022-12-09 17:02 UTC, bayological requested changes

2022-12-12 09:44 UTC, bowd commented on contracts/common/breakers/WithCooldown.sol
> +contract WithCooldown {
I wish I could but I can't.

2022-12-13 13:38 UTC, bayological approved these changes
LGTM

2022-12-14 13:50 UTC, merged